name: Send email
on:
  push:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  run_extract_load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt          

      - name: Extract and load
        run: python ./src/extract_load.py    
        env:
          GOODDATA_HOST: ${{ secrets.GOODDATA_HOST }}
          GOODDATA_TOKEN: ${{ secrets.GOODDATA_TOKEN }}
          GOODDATA_WORKSPACE_ID: ${{ secrets.GOODDATA_WORKSPACE_ID }}
          GOODDATA_VISUALIZATION_ID: ${{ secrets.GOODDATA_VISUALIZATION_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}